package cn.edu.nju.software.judge.beans;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Article implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _article.article_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _article.user_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _article.user_name
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _article.title
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _article.open
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer open;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _article.sort_num
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer sortNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _article.state
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _article.add_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private LocalDateTime addDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _article.update_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private LocalDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _article.del
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer del;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _article.content
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _article
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _article.article_id
     *
     * @return the value of _article.article_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _article.article_id
     *
     * @param articleId the value for _article.article_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _article.user_id
     *
     * @return the value of _article.user_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _article.user_id
     *
     * @param userId the value for _article.user_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _article.user_name
     *
     * @return the value of _article.user_name
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _article.user_name
     *
     * @param userName the value for _article.user_name
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _article.title
     *
     * @return the value of _article.title
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _article.title
     *
     * @param title the value for _article.title
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _article.open
     *
     * @return the value of _article.open
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getOpen() {
        return open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _article.open
     *
     * @param open the value for _article.open
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setOpen(Integer open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _article.sort_num
     *
     * @return the value of _article.sort_num
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _article.sort_num
     *
     * @param sortNum the value for _article.sort_num
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _article.state
     *
     * @return the value of _article.state
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _article.state
     *
     * @param state the value for _article.state
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _article.add_datetime
     *
     * @return the value of _article.add_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public LocalDateTime getAddDatetime() {
        return addDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _article.add_datetime
     *
     * @param addDatetime the value for _article.add_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setAddDatetime(LocalDateTime addDatetime) {
        this.addDatetime = addDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _article.update_datetime
     *
     * @return the value of _article.update_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public LocalDateTime getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _article.update_datetime
     *
     * @param updateDatetime the value for _article.update_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setUpdateDatetime(LocalDateTime updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _article.del
     *
     * @return the value of _article.del
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _article.del
     *
     * @param del the value for _article.del
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _article.content
     *
     * @return the value of _article.content
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _article.content
     *
     * @param content the value for _article.content
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _article
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Article other = (Article) that;
        return (this.getArticleId() == null ? other.getArticleId() == null : this.getArticleId().equals(other.getArticleId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getOpen() == null ? other.getOpen() == null : this.getOpen().equals(other.getOpen()))
            && (this.getSortNum() == null ? other.getSortNum() == null : this.getSortNum().equals(other.getSortNum()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getAddDatetime() == null ? other.getAddDatetime() == null : this.getAddDatetime().equals(other.getAddDatetime()))
            && (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null : this.getUpdateDatetime().equals(other.getUpdateDatetime()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _article
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getArticleId() == null) ? 0 : getArticleId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getOpen() == null) ? 0 : getOpen().hashCode());
        result = prime * result + ((getSortNum() == null) ? 0 : getSortNum().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getAddDatetime() == null) ? 0 : getAddDatetime().hashCode());
        result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }
}