package cn.edu.nju.software.judge.beans;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Contest implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.contest_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer contestId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.user_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.user_name
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.contest_type
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer contestType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.title
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.password
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.begin_time
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private LocalDateTime beginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.end_time
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private LocalDateTime endTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.hash_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String hashCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.langmask
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer langmask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.access_permission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer accessPermission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.history_rank
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer historyRank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.state
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.sort_num
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer sortNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.add_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private LocalDateTime addDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.update_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private LocalDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.del
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer del;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.contest_id
     *
     * @return the value of _contest.contest_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getContestId() {
        return contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.contest_id
     *
     * @param contestId the value for _contest.contest_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setContestId(Integer contestId) {
        this.contestId = contestId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.user_id
     *
     * @return the value of _contest.user_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.user_id
     *
     * @param userId the value for _contest.user_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.user_name
     *
     * @return the value of _contest.user_name
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.user_name
     *
     * @param userName the value for _contest.user_name
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.contest_type
     *
     * @return the value of _contest.contest_type
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getContestType() {
        return contestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.contest_type
     *
     * @param contestType the value for _contest.contest_type
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setContestType(Integer contestType) {
        this.contestType = contestType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.title
     *
     * @return the value of _contest.title
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.title
     *
     * @param title the value for _contest.title
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.password
     *
     * @return the value of _contest.password
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.password
     *
     * @param password the value for _contest.password
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.begin_time
     *
     * @return the value of _contest.begin_time
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public LocalDateTime getBeginTime() {
        return beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.begin_time
     *
     * @param beginTime the value for _contest.begin_time
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setBeginTime(LocalDateTime beginTime) {
        this.beginTime = beginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.end_time
     *
     * @return the value of _contest.end_time
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public LocalDateTime getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.end_time
     *
     * @param endTime the value for _contest.end_time
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setEndTime(LocalDateTime endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.hash_code
     *
     * @return the value of _contest.hash_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public String getHashCode() {
        return hashCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.hash_code
     *
     * @param hashCode the value for _contest.hash_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setHashCode(String hashCode) {
        this.hashCode = hashCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.langmask
     *
     * @return the value of _contest.langmask
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getLangmask() {
        return langmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.langmask
     *
     * @param langmask the value for _contest.langmask
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setLangmask(Integer langmask) {
        this.langmask = langmask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.access_permission
     *
     * @return the value of _contest.access_permission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getAccessPermission() {
        return accessPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.access_permission
     *
     * @param accessPermission the value for _contest.access_permission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setAccessPermission(Integer accessPermission) {
        this.accessPermission = accessPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.history_rank
     *
     * @return the value of _contest.history_rank
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getHistoryRank() {
        return historyRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.history_rank
     *
     * @param historyRank the value for _contest.history_rank
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setHistoryRank(Integer historyRank) {
        this.historyRank = historyRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.state
     *
     * @return the value of _contest.state
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.state
     *
     * @param state the value for _contest.state
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.sort_num
     *
     * @return the value of _contest.sort_num
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getSortNum() {
        return sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.sort_num
     *
     * @param sortNum the value for _contest.sort_num
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setSortNum(Integer sortNum) {
        this.sortNum = sortNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.add_datetime
     *
     * @return the value of _contest.add_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public LocalDateTime getAddDatetime() {
        return addDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.add_datetime
     *
     * @param addDatetime the value for _contest.add_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setAddDatetime(LocalDateTime addDatetime) {
        this.addDatetime = addDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.update_datetime
     *
     * @return the value of _contest.update_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public LocalDateTime getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.update_datetime
     *
     * @param updateDatetime the value for _contest.update_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setUpdateDatetime(LocalDateTime updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.del
     *
     * @return the value of _contest.del
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.del
     *
     * @param del the value for _contest.del
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Contest other = (Contest) that;
        return (this.getContestId() == null ? other.getContestId() == null : this.getContestId().equals(other.getContestId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getContestType() == null ? other.getContestType() == null : this.getContestType().equals(other.getContestType()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getBeginTime() == null ? other.getBeginTime() == null : this.getBeginTime().equals(other.getBeginTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getHashCode() == null ? other.getHashCode() == null : this.getHashCode().equals(other.getHashCode()))
            && (this.getLangmask() == null ? other.getLangmask() == null : this.getLangmask().equals(other.getLangmask()))
            && (this.getAccessPermission() == null ? other.getAccessPermission() == null : this.getAccessPermission().equals(other.getAccessPermission()))
            && (this.getHistoryRank() == null ? other.getHistoryRank() == null : this.getHistoryRank().equals(other.getHistoryRank()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getSortNum() == null ? other.getSortNum() == null : this.getSortNum().equals(other.getSortNum()))
            && (this.getAddDatetime() == null ? other.getAddDatetime() == null : this.getAddDatetime().equals(other.getAddDatetime()))
            && (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null : this.getUpdateDatetime().equals(other.getUpdateDatetime()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getContestId() == null) ? 0 : getContestId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getContestType() == null) ? 0 : getContestType().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getBeginTime() == null) ? 0 : getBeginTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getHashCode() == null) ? 0 : getHashCode().hashCode());
        result = prime * result + ((getLangmask() == null) ? 0 : getLangmask().hashCode());
        result = prime * result + ((getAccessPermission() == null) ? 0 : getAccessPermission().hashCode());
        result = prime * result + ((getHistoryRank() == null) ? 0 : getHistoryRank().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getSortNum() == null) ? 0 : getSortNum().hashCode());
        result = prime * result + ((getAddDatetime() == null) ? 0 : getAddDatetime().hashCode());
        result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        return result;
    }
}