package cn.edu.nju.software.judge.beans;

import java.io.Serializable;

public class ContestWithBLOBs extends Contest implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.description
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _contest.announcement
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String announcement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.description
     *
     * @return the value of _contest.description
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.description
     *
     * @param description the value for _contest.description
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _contest.announcement
     *
     * @return the value of _contest.announcement
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public String getAnnouncement() {
        return announcement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _contest.announcement
     *
     * @param announcement the value for _contest.announcement
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setAnnouncement(String announcement) {
        this.announcement = announcement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        ContestWithBLOBs other = (ContestWithBLOBs) that;
        return (this.getContestId() == null ? other.getContestId() == null : this.getContestId().equals(other.getContestId()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getContestType() == null ? other.getContestType() == null : this.getContestType().equals(other.getContestType()))
            && (this.getTitle() == null ? other.getTitle() == null : this.getTitle().equals(other.getTitle()))
            && (this.getPassword() == null ? other.getPassword() == null : this.getPassword().equals(other.getPassword()))
            && (this.getBeginTime() == null ? other.getBeginTime() == null : this.getBeginTime().equals(other.getBeginTime()))
            && (this.getEndTime() == null ? other.getEndTime() == null : this.getEndTime().equals(other.getEndTime()))
            && (this.getHashCode() == null ? other.getHashCode() == null : this.getHashCode().equals(other.getHashCode()))
            && (this.getLangmask() == null ? other.getLangmask() == null : this.getLangmask().equals(other.getLangmask()))
            && (this.getAccessPermission() == null ? other.getAccessPermission() == null : this.getAccessPermission().equals(other.getAccessPermission()))
            && (this.getHistoryRank() == null ? other.getHistoryRank() == null : this.getHistoryRank().equals(other.getHistoryRank()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getSortNum() == null ? other.getSortNum() == null : this.getSortNum().equals(other.getSortNum()))
            && (this.getAddDatetime() == null ? other.getAddDatetime() == null : this.getAddDatetime().equals(other.getAddDatetime()))
            && (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null : this.getUpdateDatetime().equals(other.getUpdateDatetime()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getAnnouncement() == null ? other.getAnnouncement() == null : this.getAnnouncement().equals(other.getAnnouncement()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getContestId() == null) ? 0 : getContestId().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getContestType() == null) ? 0 : getContestType().hashCode());
        result = prime * result + ((getTitle() == null) ? 0 : getTitle().hashCode());
        result = prime * result + ((getPassword() == null) ? 0 : getPassword().hashCode());
        result = prime * result + ((getBeginTime() == null) ? 0 : getBeginTime().hashCode());
        result = prime * result + ((getEndTime() == null) ? 0 : getEndTime().hashCode());
        result = prime * result + ((getHashCode() == null) ? 0 : getHashCode().hashCode());
        result = prime * result + ((getLangmask() == null) ? 0 : getLangmask().hashCode());
        result = prime * result + ((getAccessPermission() == null) ? 0 : getAccessPermission().hashCode());
        result = prime * result + ((getHistoryRank() == null) ? 0 : getHistoryRank().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getSortNum() == null) ? 0 : getSortNum().hashCode());
        result = prime * result + ((getAddDatetime() == null) ? 0 : getAddDatetime().hashCode());
        result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getAnnouncement() == null) ? 0 : getAnnouncement().hashCode());
        return result;
    }
}