package cn.edu.nju.software.judge.beans;

import java.io.Serializable;
import java.time.LocalDateTime;

public class Reply implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _reply.rid
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _reply.user_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _reply.user_name
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String userName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _reply.prid
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer prid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _reply.puser_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer puserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _reply.puser_name
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String puserName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _reply.article_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer articleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _reply.status
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _reply.add_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private LocalDateTime addDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _reply.update_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private LocalDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _reply.del
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer del;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _reply.content
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _reply
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _reply.rid
     *
     * @return the value of _reply.rid
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _reply.rid
     *
     * @param rid the value for _reply.rid
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setRid(Integer rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _reply.user_id
     *
     * @return the value of _reply.user_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _reply.user_id
     *
     * @param userId the value for _reply.user_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _reply.user_name
     *
     * @return the value of _reply.user_name
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _reply.user_name
     *
     * @param userName the value for _reply.user_name
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _reply.prid
     *
     * @return the value of _reply.prid
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getPrid() {
        return prid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _reply.prid
     *
     * @param prid the value for _reply.prid
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setPrid(Integer prid) {
        this.prid = prid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _reply.puser_id
     *
     * @return the value of _reply.puser_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getPuserId() {
        return puserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _reply.puser_id
     *
     * @param puserId the value for _reply.puser_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setPuserId(Integer puserId) {
        this.puserId = puserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _reply.puser_name
     *
     * @return the value of _reply.puser_name
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public String getPuserName() {
        return puserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _reply.puser_name
     *
     * @param puserName the value for _reply.puser_name
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setPuserName(String puserName) {
        this.puserName = puserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _reply.article_id
     *
     * @return the value of _reply.article_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getArticleId() {
        return articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _reply.article_id
     *
     * @param articleId the value for _reply.article_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setArticleId(Integer articleId) {
        this.articleId = articleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _reply.status
     *
     * @return the value of _reply.status
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _reply.status
     *
     * @param status the value for _reply.status
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _reply.add_datetime
     *
     * @return the value of _reply.add_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public LocalDateTime getAddDatetime() {
        return addDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _reply.add_datetime
     *
     * @param addDatetime the value for _reply.add_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setAddDatetime(LocalDateTime addDatetime) {
        this.addDatetime = addDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _reply.update_datetime
     *
     * @return the value of _reply.update_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public LocalDateTime getUpdateDatetime() {
        return updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _reply.update_datetime
     *
     * @param updateDatetime the value for _reply.update_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setUpdateDatetime(LocalDateTime updateDatetime) {
        this.updateDatetime = updateDatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _reply.del
     *
     * @return the value of _reply.del
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getDel() {
        return del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _reply.del
     *
     * @param del the value for _reply.del
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setDel(Integer del) {
        this.del = del;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _reply.content
     *
     * @return the value of _reply.content
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _reply.content
     *
     * @param content the value for _reply.content
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _reply
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Reply other = (Reply) that;
        return (this.getRid() == null ? other.getRid() == null : this.getRid().equals(other.getRid()))
            && (this.getUserId() == null ? other.getUserId() == null : this.getUserId().equals(other.getUserId()))
            && (this.getUserName() == null ? other.getUserName() == null : this.getUserName().equals(other.getUserName()))
            && (this.getPrid() == null ? other.getPrid() == null : this.getPrid().equals(other.getPrid()))
            && (this.getPuserId() == null ? other.getPuserId() == null : this.getPuserId().equals(other.getPuserId()))
            && (this.getPuserName() == null ? other.getPuserName() == null : this.getPuserName().equals(other.getPuserName()))
            && (this.getArticleId() == null ? other.getArticleId() == null : this.getArticleId().equals(other.getArticleId()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getAddDatetime() == null ? other.getAddDatetime() == null : this.getAddDatetime().equals(other.getAddDatetime()))
            && (this.getUpdateDatetime() == null ? other.getUpdateDatetime() == null : this.getUpdateDatetime().equals(other.getUpdateDatetime()))
            && (this.getDel() == null ? other.getDel() == null : this.getDel().equals(other.getDel()))
            && (this.getContent() == null ? other.getContent() == null : this.getContent().equals(other.getContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _reply
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRid() == null) ? 0 : getRid().hashCode());
        result = prime * result + ((getUserId() == null) ? 0 : getUserId().hashCode());
        result = prime * result + ((getUserName() == null) ? 0 : getUserName().hashCode());
        result = prime * result + ((getPrid() == null) ? 0 : getPrid().hashCode());
        result = prime * result + ((getPuserId() == null) ? 0 : getPuserId().hashCode());
        result = prime * result + ((getPuserName() == null) ? 0 : getPuserName().hashCode());
        result = prime * result + ((getArticleId() == null) ? 0 : getArticleId().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getAddDatetime() == null) ? 0 : getAddDatetime().hashCode());
        result = prime * result + ((getUpdateDatetime() == null) ? 0 : getUpdateDatetime().hashCode());
        result = prime * result + ((getDel() == null) ? 0 : getDel().hashCode());
        result = prime * result + ((getContent() == null) ? 0 : getContent().hashCode());
        return result;
    }
}