package cn.edu.nju.software.judge.beans;

import java.io.Serializable;

public class Sim implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _sim.s_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer sId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _sim.sim_s_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer simSId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _sim.sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer sim;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _sim.s_id
     *
     * @return the value of _sim.s_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getsId() {
        return sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _sim.s_id
     *
     * @param sId the value for _sim.s_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setsId(Integer sId) {
        this.sId = sId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _sim.sim_s_id
     *
     * @return the value of _sim.sim_s_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getSimSId() {
        return simSId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _sim.sim_s_id
     *
     * @param simSId the value for _sim.sim_s_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setSimSId(Integer simSId) {
        this.simSId = simSId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _sim.sim
     *
     * @return the value of _sim.sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Integer getSim() {
        return sim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _sim.sim
     *
     * @param sim the value for _sim.sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setSim(Integer sim) {
        this.sim = sim;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Sim other = (Sim) that;
        return (this.getsId() == null ? other.getsId() == null : this.getsId().equals(other.getsId()))
            && (this.getSimSId() == null ? other.getSimSId() == null : this.getSimSId().equals(other.getSimSId()))
            && (this.getSim() == null ? other.getSim() == null : this.getSim().equals(other.getSim()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getsId() == null) ? 0 : getsId().hashCode());
        result = prime * result + ((getSimSId() == null) ? 0 : getSimSId().hashCode());
        result = prime * result + ((getSim() == null) ? 0 : getSim().hashCode());
        return result;
    }
}