package cn.edu.nju.software.judge.beans;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class SubmissionExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public SubmissionExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andSubmissionIdIsNull() {
            addCriterion("submission_id is null");
            return (Criteria) this;
        }

        public Criteria andSubmissionIdIsNotNull() {
            addCriterion("submission_id is not null");
            return (Criteria) this;
        }

        public Criteria andSubmissionIdEqualTo(Integer value) {
            addCriterion("submission_id =", value, "submissionId");
            return (Criteria) this;
        }

        public Criteria andSubmissionIdNotEqualTo(Integer value) {
            addCriterion("submission_id <>", value, "submissionId");
            return (Criteria) this;
        }

        public Criteria andSubmissionIdGreaterThan(Integer value) {
            addCriterion("submission_id >", value, "submissionId");
            return (Criteria) this;
        }

        public Criteria andSubmissionIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("submission_id >=", value, "submissionId");
            return (Criteria) this;
        }

        public Criteria andSubmissionIdLessThan(Integer value) {
            addCriterion("submission_id <", value, "submissionId");
            return (Criteria) this;
        }

        public Criteria andSubmissionIdLessThanOrEqualTo(Integer value) {
            addCriterion("submission_id <=", value, "submissionId");
            return (Criteria) this;
        }

        public Criteria andSubmissionIdIn(List<Integer> values) {
            addCriterion("submission_id in", values, "submissionId");
            return (Criteria) this;
        }

        public Criteria andSubmissionIdNotIn(List<Integer> values) {
            addCriterion("submission_id not in", values, "submissionId");
            return (Criteria) this;
        }

        public Criteria andSubmissionIdBetween(Integer value1, Integer value2) {
            addCriterion("submission_id between", value1, value2, "submissionId");
            return (Criteria) this;
        }

        public Criteria andSubmissionIdNotBetween(Integer value1, Integer value2) {
            addCriterion("submission_id not between", value1, value2, "submissionId");
            return (Criteria) this;
        }

        public Criteria andProblemIdIsNull() {
            addCriterion("problem_id is null");
            return (Criteria) this;
        }

        public Criteria andProblemIdIsNotNull() {
            addCriterion("problem_id is not null");
            return (Criteria) this;
        }

        public Criteria andProblemIdEqualTo(Integer value) {
            addCriterion("problem_id =", value, "problemId");
            return (Criteria) this;
        }

        public Criteria andProblemIdNotEqualTo(Integer value) {
            addCriterion("problem_id <>", value, "problemId");
            return (Criteria) this;
        }

        public Criteria andProblemIdGreaterThan(Integer value) {
            addCriterion("problem_id >", value, "problemId");
            return (Criteria) this;
        }

        public Criteria andProblemIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("problem_id >=", value, "problemId");
            return (Criteria) this;
        }

        public Criteria andProblemIdLessThan(Integer value) {
            addCriterion("problem_id <", value, "problemId");
            return (Criteria) this;
        }

        public Criteria andProblemIdLessThanOrEqualTo(Integer value) {
            addCriterion("problem_id <=", value, "problemId");
            return (Criteria) this;
        }

        public Criteria andProblemIdIn(List<Integer> values) {
            addCriterion("problem_id in", values, "problemId");
            return (Criteria) this;
        }

        public Criteria andProblemIdNotIn(List<Integer> values) {
            addCriterion("problem_id not in", values, "problemId");
            return (Criteria) this;
        }

        public Criteria andProblemIdBetween(Integer value1, Integer value2) {
            addCriterion("problem_id between", value1, value2, "problemId");
            return (Criteria) this;
        }

        public Criteria andProblemIdNotBetween(Integer value1, Integer value2) {
            addCriterion("problem_id not between", value1, value2, "problemId");
            return (Criteria) this;
        }

        public Criteria andContestIdIsNull() {
            addCriterion("contest_id is null");
            return (Criteria) this;
        }

        public Criteria andContestIdIsNotNull() {
            addCriterion("contest_id is not null");
            return (Criteria) this;
        }

        public Criteria andContestIdEqualTo(Integer value) {
            addCriterion("contest_id =", value, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdNotEqualTo(Integer value) {
            addCriterion("contest_id <>", value, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdGreaterThan(Integer value) {
            addCriterion("contest_id >", value, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("contest_id >=", value, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdLessThan(Integer value) {
            addCriterion("contest_id <", value, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdLessThanOrEqualTo(Integer value) {
            addCriterion("contest_id <=", value, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdIn(List<Integer> values) {
            addCriterion("contest_id in", values, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdNotIn(List<Integer> values) {
            addCriterion("contest_id not in", values, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdBetween(Integer value1, Integer value2) {
            addCriterion("contest_id between", value1, value2, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestIdNotBetween(Integer value1, Integer value2) {
            addCriterion("contest_id not between", value1, value2, "contestId");
            return (Criteria) this;
        }

        public Criteria andContestNumIsNull() {
            addCriterion("contest_num is null");
            return (Criteria) this;
        }

        public Criteria andContestNumIsNotNull() {
            addCriterion("contest_num is not null");
            return (Criteria) this;
        }

        public Criteria andContestNumEqualTo(String value) {
            addCriterion("contest_num =", value, "contestNum");
            return (Criteria) this;
        }

        public Criteria andContestNumNotEqualTo(String value) {
            addCriterion("contest_num <>", value, "contestNum");
            return (Criteria) this;
        }

        public Criteria andContestNumGreaterThan(String value) {
            addCriterion("contest_num >", value, "contestNum");
            return (Criteria) this;
        }

        public Criteria andContestNumGreaterThanOrEqualTo(String value) {
            addCriterion("contest_num >=", value, "contestNum");
            return (Criteria) this;
        }

        public Criteria andContestNumLessThan(String value) {
            addCriterion("contest_num <", value, "contestNum");
            return (Criteria) this;
        }

        public Criteria andContestNumLessThanOrEqualTo(String value) {
            addCriterion("contest_num <=", value, "contestNum");
            return (Criteria) this;
        }

        public Criteria andContestNumLike(String value) {
            addCriterion("contest_num like", value, "contestNum");
            return (Criteria) this;
        }

        public Criteria andContestNumNotLike(String value) {
            addCriterion("contest_num not like", value, "contestNum");
            return (Criteria) this;
        }

        public Criteria andContestNumIn(List<String> values) {
            addCriterion("contest_num in", values, "contestNum");
            return (Criteria) this;
        }

        public Criteria andContestNumNotIn(List<String> values) {
            addCriterion("contest_num not in", values, "contestNum");
            return (Criteria) this;
        }

        public Criteria andContestNumBetween(String value1, String value2) {
            addCriterion("contest_num between", value1, value2, "contestNum");
            return (Criteria) this;
        }

        public Criteria andContestNumNotBetween(String value1, String value2) {
            addCriterion("contest_num not between", value1, value2, "contestNum");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNull() {
            addCriterion("user_name is null");
            return (Criteria) this;
        }

        public Criteria andUserNameIsNotNull() {
            addCriterion("user_name is not null");
            return (Criteria) this;
        }

        public Criteria andUserNameEqualTo(String value) {
            addCriterion("user_name =", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotEqualTo(String value) {
            addCriterion("user_name <>", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThan(String value) {
            addCriterion("user_name >", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("user_name >=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThan(String value) {
            addCriterion("user_name <", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLessThanOrEqualTo(String value) {
            addCriterion("user_name <=", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameLike(String value) {
            addCriterion("user_name like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotLike(String value) {
            addCriterion("user_name not like", value, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameIn(List<String> values) {
            addCriterion("user_name in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotIn(List<String> values) {
            addCriterion("user_name not in", values, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameBetween(String value1, String value2) {
            addCriterion("user_name between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andUserNameNotBetween(String value1, String value2) {
            addCriterion("user_name not between", value1, value2, "userName");
            return (Criteria) this;
        }

        public Criteria andResultIsNull() {
            addCriterion("result is null");
            return (Criteria) this;
        }

        public Criteria andResultIsNotNull() {
            addCriterion("result is not null");
            return (Criteria) this;
        }

        public Criteria andResultEqualTo(Short value) {
            addCriterion("result =", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotEqualTo(Short value) {
            addCriterion("result <>", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThan(Short value) {
            addCriterion("result >", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultGreaterThanOrEqualTo(Short value) {
            addCriterion("result >=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThan(Short value) {
            addCriterion("result <", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultLessThanOrEqualTo(Short value) {
            addCriterion("result <=", value, "result");
            return (Criteria) this;
        }

        public Criteria andResultIn(List<Short> values) {
            addCriterion("result in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotIn(List<Short> values) {
            addCriterion("result not in", values, "result");
            return (Criteria) this;
        }

        public Criteria andResultBetween(Short value1, Short value2) {
            addCriterion("result between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andResultNotBetween(Short value1, Short value2) {
            addCriterion("result not between", value1, value2, "result");
            return (Criteria) this;
        }

        public Criteria andTimeIsNull() {
            addCriterion("time is null");
            return (Criteria) this;
        }

        public Criteria andTimeIsNotNull() {
            addCriterion("time is not null");
            return (Criteria) this;
        }

        public Criteria andTimeEqualTo(Integer value) {
            addCriterion("time =", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotEqualTo(Integer value) {
            addCriterion("time <>", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThan(Integer value) {
            addCriterion("time >", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeGreaterThanOrEqualTo(Integer value) {
            addCriterion("time >=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThan(Integer value) {
            addCriterion("time <", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeLessThanOrEqualTo(Integer value) {
            addCriterion("time <=", value, "time");
            return (Criteria) this;
        }

        public Criteria andTimeIn(List<Integer> values) {
            addCriterion("time in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotIn(List<Integer> values) {
            addCriterion("time not in", values, "time");
            return (Criteria) this;
        }

        public Criteria andTimeBetween(Integer value1, Integer value2) {
            addCriterion("time between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andTimeNotBetween(Integer value1, Integer value2) {
            addCriterion("time not between", value1, value2, "time");
            return (Criteria) this;
        }

        public Criteria andMemoryIsNull() {
            addCriterion("memory is null");
            return (Criteria) this;
        }

        public Criteria andMemoryIsNotNull() {
            addCriterion("memory is not null");
            return (Criteria) this;
        }

        public Criteria andMemoryEqualTo(Integer value) {
            addCriterion("memory =", value, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryNotEqualTo(Integer value) {
            addCriterion("memory <>", value, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryGreaterThan(Integer value) {
            addCriterion("memory >", value, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryGreaterThanOrEqualTo(Integer value) {
            addCriterion("memory >=", value, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryLessThan(Integer value) {
            addCriterion("memory <", value, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryLessThanOrEqualTo(Integer value) {
            addCriterion("memory <=", value, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryIn(List<Integer> values) {
            addCriterion("memory in", values, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryNotIn(List<Integer> values) {
            addCriterion("memory not in", values, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryBetween(Integer value1, Integer value2) {
            addCriterion("memory between", value1, value2, "memory");
            return (Criteria) this;
        }

        public Criteria andMemoryNotBetween(Integer value1, Integer value2) {
            addCriterion("memory not between", value1, value2, "memory");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeIsNull() {
            addCriterion("submit_time is null");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeIsNotNull() {
            addCriterion("submit_time is not null");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeEqualTo(LocalDateTime value) {
            addCriterion("submit_time =", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeNotEqualTo(LocalDateTime value) {
            addCriterion("submit_time <>", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeGreaterThan(LocalDateTime value) {
            addCriterion("submit_time >", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("submit_time >=", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeLessThan(LocalDateTime value) {
            addCriterion("submit_time <", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("submit_time <=", value, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeIn(List<LocalDateTime> values) {
            addCriterion("submit_time in", values, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeNotIn(List<LocalDateTime> values) {
            addCriterion("submit_time not in", values, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("submit_time between", value1, value2, "submitTime");
            return (Criteria) this;
        }

        public Criteria andSubmitTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("submit_time not between", value1, value2, "submitTime");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNull() {
            addCriterion("language is null");
            return (Criteria) this;
        }

        public Criteria andLanguageIsNotNull() {
            addCriterion("language is not null");
            return (Criteria) this;
        }

        public Criteria andLanguageEqualTo(Integer value) {
            addCriterion("language =", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotEqualTo(Integer value) {
            addCriterion("language <>", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThan(Integer value) {
            addCriterion("language >", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageGreaterThanOrEqualTo(Integer value) {
            addCriterion("language >=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThan(Integer value) {
            addCriterion("language <", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageLessThanOrEqualTo(Integer value) {
            addCriterion("language <=", value, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageIn(List<Integer> values) {
            addCriterion("language in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotIn(List<Integer> values) {
            addCriterion("language not in", values, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageBetween(Integer value1, Integer value2) {
            addCriterion("language between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andLanguageNotBetween(Integer value1, Integer value2) {
            addCriterion("language not between", value1, value2, "language");
            return (Criteria) this;
        }

        public Criteria andOpenIsNull() {
            addCriterion("open is null");
            return (Criteria) this;
        }

        public Criteria andOpenIsNotNull() {
            addCriterion("open is not null");
            return (Criteria) this;
        }

        public Criteria andOpenEqualTo(Short value) {
            addCriterion("open =", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenNotEqualTo(Short value) {
            addCriterion("open <>", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenGreaterThan(Short value) {
            addCriterion("open >", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenGreaterThanOrEqualTo(Short value) {
            addCriterion("open >=", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenLessThan(Short value) {
            addCriterion("open <", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenLessThanOrEqualTo(Short value) {
            addCriterion("open <=", value, "open");
            return (Criteria) this;
        }

        public Criteria andOpenIn(List<Short> values) {
            addCriterion("open in", values, "open");
            return (Criteria) this;
        }

        public Criteria andOpenNotIn(List<Short> values) {
            addCriterion("open not in", values, "open");
            return (Criteria) this;
        }

        public Criteria andOpenBetween(Short value1, Short value2) {
            addCriterion("open between", value1, value2, "open");
            return (Criteria) this;
        }

        public Criteria andOpenNotBetween(Short value1, Short value2) {
            addCriterion("open not between", value1, value2, "open");
            return (Criteria) this;
        }

        public Criteria andDispLanguageIsNull() {
            addCriterion("disp_language is null");
            return (Criteria) this;
        }

        public Criteria andDispLanguageIsNotNull() {
            addCriterion("disp_language is not null");
            return (Criteria) this;
        }

        public Criteria andDispLanguageEqualTo(String value) {
            addCriterion("disp_language =", value, "dispLanguage");
            return (Criteria) this;
        }

        public Criteria andDispLanguageNotEqualTo(String value) {
            addCriterion("disp_language <>", value, "dispLanguage");
            return (Criteria) this;
        }

        public Criteria andDispLanguageGreaterThan(String value) {
            addCriterion("disp_language >", value, "dispLanguage");
            return (Criteria) this;
        }

        public Criteria andDispLanguageGreaterThanOrEqualTo(String value) {
            addCriterion("disp_language >=", value, "dispLanguage");
            return (Criteria) this;
        }

        public Criteria andDispLanguageLessThan(String value) {
            addCriterion("disp_language <", value, "dispLanguage");
            return (Criteria) this;
        }

        public Criteria andDispLanguageLessThanOrEqualTo(String value) {
            addCriterion("disp_language <=", value, "dispLanguage");
            return (Criteria) this;
        }

        public Criteria andDispLanguageLike(String value) {
            addCriterion("disp_language like", value, "dispLanguage");
            return (Criteria) this;
        }

        public Criteria andDispLanguageNotLike(String value) {
            addCriterion("disp_language not like", value, "dispLanguage");
            return (Criteria) this;
        }

        public Criteria andDispLanguageIn(List<String> values) {
            addCriterion("disp_language in", values, "dispLanguage");
            return (Criteria) this;
        }

        public Criteria andDispLanguageNotIn(List<String> values) {
            addCriterion("disp_language not in", values, "dispLanguage");
            return (Criteria) this;
        }

        public Criteria andDispLanguageBetween(String value1, String value2) {
            addCriterion("disp_language between", value1, value2, "dispLanguage");
            return (Criteria) this;
        }

        public Criteria andDispLanguageNotBetween(String value1, String value2) {
            addCriterion("disp_language not between", value1, value2, "dispLanguage");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andStatusCanonicalIsNull() {
            addCriterion("status_canonical is null");
            return (Criteria) this;
        }

        public Criteria andStatusCanonicalIsNotNull() {
            addCriterion("status_canonical is not null");
            return (Criteria) this;
        }

        public Criteria andStatusCanonicalEqualTo(String value) {
            addCriterion("status_canonical =", value, "statusCanonical");
            return (Criteria) this;
        }

        public Criteria andStatusCanonicalNotEqualTo(String value) {
            addCriterion("status_canonical <>", value, "statusCanonical");
            return (Criteria) this;
        }

        public Criteria andStatusCanonicalGreaterThan(String value) {
            addCriterion("status_canonical >", value, "statusCanonical");
            return (Criteria) this;
        }

        public Criteria andStatusCanonicalGreaterThanOrEqualTo(String value) {
            addCriterion("status_canonical >=", value, "statusCanonical");
            return (Criteria) this;
        }

        public Criteria andStatusCanonicalLessThan(String value) {
            addCriterion("status_canonical <", value, "statusCanonical");
            return (Criteria) this;
        }

        public Criteria andStatusCanonicalLessThanOrEqualTo(String value) {
            addCriterion("status_canonical <=", value, "statusCanonical");
            return (Criteria) this;
        }

        public Criteria andStatusCanonicalLike(String value) {
            addCriterion("status_canonical like", value, "statusCanonical");
            return (Criteria) this;
        }

        public Criteria andStatusCanonicalNotLike(String value) {
            addCriterion("status_canonical not like", value, "statusCanonical");
            return (Criteria) this;
        }

        public Criteria andStatusCanonicalIn(List<String> values) {
            addCriterion("status_canonical in", values, "statusCanonical");
            return (Criteria) this;
        }

        public Criteria andStatusCanonicalNotIn(List<String> values) {
            addCriterion("status_canonical not in", values, "statusCanonical");
            return (Criteria) this;
        }

        public Criteria andStatusCanonicalBetween(String value1, String value2) {
            addCriterion("status_canonical between", value1, value2, "statusCanonical");
            return (Criteria) this;
        }

        public Criteria andStatusCanonicalNotBetween(String value1, String value2) {
            addCriterion("status_canonical not between", value1, value2, "statusCanonical");
            return (Criteria) this;
        }

        public Criteria andSourceLengthIsNull() {
            addCriterion("source_length is null");
            return (Criteria) this;
        }

        public Criteria andSourceLengthIsNotNull() {
            addCriterion("source_length is not null");
            return (Criteria) this;
        }

        public Criteria andSourceLengthEqualTo(Integer value) {
            addCriterion("source_length =", value, "sourceLength");
            return (Criteria) this;
        }

        public Criteria andSourceLengthNotEqualTo(Integer value) {
            addCriterion("source_length <>", value, "sourceLength");
            return (Criteria) this;
        }

        public Criteria andSourceLengthGreaterThan(Integer value) {
            addCriterion("source_length >", value, "sourceLength");
            return (Criteria) this;
        }

        public Criteria andSourceLengthGreaterThanOrEqualTo(Integer value) {
            addCriterion("source_length >=", value, "sourceLength");
            return (Criteria) this;
        }

        public Criteria andSourceLengthLessThan(Integer value) {
            addCriterion("source_length <", value, "sourceLength");
            return (Criteria) this;
        }

        public Criteria andSourceLengthLessThanOrEqualTo(Integer value) {
            addCriterion("source_length <=", value, "sourceLength");
            return (Criteria) this;
        }

        public Criteria andSourceLengthIn(List<Integer> values) {
            addCriterion("source_length in", values, "sourceLength");
            return (Criteria) this;
        }

        public Criteria andSourceLengthNotIn(List<Integer> values) {
            addCriterion("source_length not in", values, "sourceLength");
            return (Criteria) this;
        }

        public Criteria andSourceLengthBetween(Integer value1, Integer value2) {
            addCriterion("source_length between", value1, value2, "sourceLength");
            return (Criteria) this;
        }

        public Criteria andSourceLengthNotBetween(Integer value1, Integer value2) {
            addCriterion("source_length not between", value1, value2, "sourceLength");
            return (Criteria) this;
        }

        public Criteria andValidIsNull() {
            addCriterion("valid is null");
            return (Criteria) this;
        }

        public Criteria andValidIsNotNull() {
            addCriterion("valid is not null");
            return (Criteria) this;
        }

        public Criteria andValidEqualTo(Byte value) {
            addCriterion("valid =", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotEqualTo(Byte value) {
            addCriterion("valid <>", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThan(Byte value) {
            addCriterion("valid >", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidGreaterThanOrEqualTo(Byte value) {
            addCriterion("valid >=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThan(Byte value) {
            addCriterion("valid <", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidLessThanOrEqualTo(Byte value) {
            addCriterion("valid <=", value, "valid");
            return (Criteria) this;
        }

        public Criteria andValidIn(List<Byte> values) {
            addCriterion("valid in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotIn(List<Byte> values) {
            addCriterion("valid not in", values, "valid");
            return (Criteria) this;
        }

        public Criteria andValidBetween(Byte value1, Byte value2) {
            addCriterion("valid between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andValidNotBetween(Byte value1, Byte value2) {
            addCriterion("valid not between", value1, value2, "valid");
            return (Criteria) this;
        }

        public Criteria andJudgeTimeIsNull() {
            addCriterion("judge_time is null");
            return (Criteria) this;
        }

        public Criteria andJudgeTimeIsNotNull() {
            addCriterion("judge_time is not null");
            return (Criteria) this;
        }

        public Criteria andJudgeTimeEqualTo(LocalDateTime value) {
            addCriterion("judge_time =", value, "judgeTime");
            return (Criteria) this;
        }

        public Criteria andJudgeTimeNotEqualTo(LocalDateTime value) {
            addCriterion("judge_time <>", value, "judgeTime");
            return (Criteria) this;
        }

        public Criteria andJudgeTimeGreaterThan(LocalDateTime value) {
            addCriterion("judge_time >", value, "judgeTime");
            return (Criteria) this;
        }

        public Criteria andJudgeTimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("judge_time >=", value, "judgeTime");
            return (Criteria) this;
        }

        public Criteria andJudgeTimeLessThan(LocalDateTime value) {
            addCriterion("judge_time <", value, "judgeTime");
            return (Criteria) this;
        }

        public Criteria andJudgeTimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("judge_time <=", value, "judgeTime");
            return (Criteria) this;
        }

        public Criteria andJudgeTimeIn(List<LocalDateTime> values) {
            addCriterion("judge_time in", values, "judgeTime");
            return (Criteria) this;
        }

        public Criteria andJudgeTimeNotIn(List<LocalDateTime> values) {
            addCriterion("judge_time not in", values, "judgeTime");
            return (Criteria) this;
        }

        public Criteria andJudgeTimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("judge_time between", value1, value2, "judgeTime");
            return (Criteria) this;
        }

        public Criteria andJudgeTimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("judge_time not between", value1, value2, "judgeTime");
            return (Criteria) this;
        }

        public Criteria andPassRateIsNull() {
            addCriterion("pass_rate is null");
            return (Criteria) this;
        }

        public Criteria andPassRateIsNotNull() {
            addCriterion("pass_rate is not null");
            return (Criteria) this;
        }

        public Criteria andPassRateEqualTo(BigDecimal value) {
            addCriterion("pass_rate =", value, "passRate");
            return (Criteria) this;
        }

        public Criteria andPassRateNotEqualTo(BigDecimal value) {
            addCriterion("pass_rate <>", value, "passRate");
            return (Criteria) this;
        }

        public Criteria andPassRateGreaterThan(BigDecimal value) {
            addCriterion("pass_rate >", value, "passRate");
            return (Criteria) this;
        }

        public Criteria andPassRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("pass_rate >=", value, "passRate");
            return (Criteria) this;
        }

        public Criteria andPassRateLessThan(BigDecimal value) {
            addCriterion("pass_rate <", value, "passRate");
            return (Criteria) this;
        }

        public Criteria andPassRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("pass_rate <=", value, "passRate");
            return (Criteria) this;
        }

        public Criteria andPassRateIn(List<BigDecimal> values) {
            addCriterion("pass_rate in", values, "passRate");
            return (Criteria) this;
        }

        public Criteria andPassRateNotIn(List<BigDecimal> values) {
            addCriterion("pass_rate not in", values, "passRate");
            return (Criteria) this;
        }

        public Criteria andPassRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pass_rate between", value1, value2, "passRate");
            return (Criteria) this;
        }

        public Criteria andPassRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("pass_rate not between", value1, value2, "passRate");
            return (Criteria) this;
        }

        public Criteria andJudgerIsNull() {
            addCriterion("judger is null");
            return (Criteria) this;
        }

        public Criteria andJudgerIsNotNull() {
            addCriterion("judger is not null");
            return (Criteria) this;
        }

        public Criteria andJudgerEqualTo(String value) {
            addCriterion("judger =", value, "judger");
            return (Criteria) this;
        }

        public Criteria andJudgerNotEqualTo(String value) {
            addCriterion("judger <>", value, "judger");
            return (Criteria) this;
        }

        public Criteria andJudgerGreaterThan(String value) {
            addCriterion("judger >", value, "judger");
            return (Criteria) this;
        }

        public Criteria andJudgerGreaterThanOrEqualTo(String value) {
            addCriterion("judger >=", value, "judger");
            return (Criteria) this;
        }

        public Criteria andJudgerLessThan(String value) {
            addCriterion("judger <", value, "judger");
            return (Criteria) this;
        }

        public Criteria andJudgerLessThanOrEqualTo(String value) {
            addCriterion("judger <=", value, "judger");
            return (Criteria) this;
        }

        public Criteria andJudgerLike(String value) {
            addCriterion("judger like", value, "judger");
            return (Criteria) this;
        }

        public Criteria andJudgerNotLike(String value) {
            addCriterion("judger not like", value, "judger");
            return (Criteria) this;
        }

        public Criteria andJudgerIn(List<String> values) {
            addCriterion("judger in", values, "judger");
            return (Criteria) this;
        }

        public Criteria andJudgerNotIn(List<String> values) {
            addCriterion("judger not in", values, "judger");
            return (Criteria) this;
        }

        public Criteria andJudgerBetween(String value1, String value2) {
            addCriterion("judger between", value1, value2, "judger");
            return (Criteria) this;
        }

        public Criteria andJudgerNotBetween(String value1, String value2) {
            addCriterion("judger not between", value1, value2, "judger");
            return (Criteria) this;
        }

        public Criteria andAddDatetimeIsNull() {
            addCriterion("add_datetime is null");
            return (Criteria) this;
        }

        public Criteria andAddDatetimeIsNotNull() {
            addCriterion("add_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andAddDatetimeEqualTo(LocalDateTime value) {
            addCriterion("add_datetime =", value, "addDatetime");
            return (Criteria) this;
        }

        public Criteria andAddDatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("add_datetime <>", value, "addDatetime");
            return (Criteria) this;
        }

        public Criteria andAddDatetimeGreaterThan(LocalDateTime value) {
            addCriterion("add_datetime >", value, "addDatetime");
            return (Criteria) this;
        }

        public Criteria andAddDatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("add_datetime >=", value, "addDatetime");
            return (Criteria) this;
        }

        public Criteria andAddDatetimeLessThan(LocalDateTime value) {
            addCriterion("add_datetime <", value, "addDatetime");
            return (Criteria) this;
        }

        public Criteria andAddDatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("add_datetime <=", value, "addDatetime");
            return (Criteria) this;
        }

        public Criteria andAddDatetimeIn(List<LocalDateTime> values) {
            addCriterion("add_datetime in", values, "addDatetime");
            return (Criteria) this;
        }

        public Criteria andAddDatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("add_datetime not in", values, "addDatetime");
            return (Criteria) this;
        }

        public Criteria andAddDatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("add_datetime between", value1, value2, "addDatetime");
            return (Criteria) this;
        }

        public Criteria andAddDatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("add_datetime not between", value1, value2, "addDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNull() {
            addCriterion("update_datetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIsNotNull() {
            addCriterion("update_datetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeEqualTo(LocalDateTime value) {
            addCriterion("update_datetime =", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotEqualTo(LocalDateTime value) {
            addCriterion("update_datetime <>", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThan(LocalDateTime value) {
            addCriterion("update_datetime >", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_datetime >=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThan(LocalDateTime value) {
            addCriterion("update_datetime <", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("update_datetime <=", value, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeIn(List<LocalDateTime> values) {
            addCriterion("update_datetime in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotIn(List<LocalDateTime> values) {
            addCriterion("update_datetime not in", values, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_datetime between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andUpdateDatetimeNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("update_datetime not between", value1, value2, "updateDatetime");
            return (Criteria) this;
        }

        public Criteria andDelIsNull() {
            addCriterion("del is null");
            return (Criteria) this;
        }

        public Criteria andDelIsNotNull() {
            addCriterion("del is not null");
            return (Criteria) this;
        }

        public Criteria andDelEqualTo(Integer value) {
            addCriterion("del =", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotEqualTo(Integer value) {
            addCriterion("del <>", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThan(Integer value) {
            addCriterion("del >", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelGreaterThanOrEqualTo(Integer value) {
            addCriterion("del >=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThan(Integer value) {
            addCriterion("del <", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelLessThanOrEqualTo(Integer value) {
            addCriterion("del <=", value, "del");
            return (Criteria) this;
        }

        public Criteria andDelIn(List<Integer> values) {
            addCriterion("del in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotIn(List<Integer> values) {
            addCriterion("del not in", values, "del");
            return (Criteria) this;
        }

        public Criteria andDelBetween(Integer value1, Integer value2) {
            addCriterion("del between", value1, value2, "del");
            return (Criteria) this;
        }

        public Criteria andDelNotBetween(Integer value1, Integer value2) {
            addCriterion("del not between", value1, value2, "del");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _submission
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 22 11:39:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table _submission
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}