package cn.edu.nju.software.judge.beans;

import java.io.Serializable;

public class Template implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.problem_id
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private Integer problemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.c_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String cTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.cc_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String ccTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.pas_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String pasTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.java_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String javaTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.rb_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String rbTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.sh_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String shTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.py_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String pyTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.py3_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String py3Template;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.php_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String phpTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.pl_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String plTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.cs_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String csTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.m_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String mTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.bas_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String basTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.scm_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String scmTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.lua_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String luaTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.js_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String jsTemplate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _template.go_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private String goTemplate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.problem_id
     *
     * @return the value of _template.problem_id
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public Integer getProblemId() {
        return problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.problem_id
     *
     * @param problemId the value for _template.problem_id
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setProblemId(Integer problemId) {
        this.problemId = problemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.c_template
     *
     * @return the value of _template.c_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getcTemplate() {
        return cTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.c_template
     *
     * @param cTemplate the value for _template.c_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setcTemplate(String cTemplate) {
        this.cTemplate = cTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.cc_template
     *
     * @return the value of _template.cc_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getCcTemplate() {
        return ccTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.cc_template
     *
     * @param ccTemplate the value for _template.cc_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setCcTemplate(String ccTemplate) {
        this.ccTemplate = ccTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.pas_template
     *
     * @return the value of _template.pas_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getPasTemplate() {
        return pasTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.pas_template
     *
     * @param pasTemplate the value for _template.pas_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setPasTemplate(String pasTemplate) {
        this.pasTemplate = pasTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.java_template
     *
     * @return the value of _template.java_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getJavaTemplate() {
        return javaTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.java_template
     *
     * @param javaTemplate the value for _template.java_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setJavaTemplate(String javaTemplate) {
        this.javaTemplate = javaTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.rb_template
     *
     * @return the value of _template.rb_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getRbTemplate() {
        return rbTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.rb_template
     *
     * @param rbTemplate the value for _template.rb_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setRbTemplate(String rbTemplate) {
        this.rbTemplate = rbTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.sh_template
     *
     * @return the value of _template.sh_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getShTemplate() {
        return shTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.sh_template
     *
     * @param shTemplate the value for _template.sh_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setShTemplate(String shTemplate) {
        this.shTemplate = shTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.py_template
     *
     * @return the value of _template.py_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getPyTemplate() {
        return pyTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.py_template
     *
     * @param pyTemplate the value for _template.py_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setPyTemplate(String pyTemplate) {
        this.pyTemplate = pyTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.py3_template
     *
     * @return the value of _template.py3_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getPy3Template() {
        return py3Template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.py3_template
     *
     * @param py3Template the value for _template.py3_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setPy3Template(String py3Template) {
        this.py3Template = py3Template;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.php_template
     *
     * @return the value of _template.php_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getPhpTemplate() {
        return phpTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.php_template
     *
     * @param phpTemplate the value for _template.php_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setPhpTemplate(String phpTemplate) {
        this.phpTemplate = phpTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.pl_template
     *
     * @return the value of _template.pl_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getPlTemplate() {
        return plTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.pl_template
     *
     * @param plTemplate the value for _template.pl_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setPlTemplate(String plTemplate) {
        this.plTemplate = plTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.cs_template
     *
     * @return the value of _template.cs_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getCsTemplate() {
        return csTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.cs_template
     *
     * @param csTemplate the value for _template.cs_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setCsTemplate(String csTemplate) {
        this.csTemplate = csTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.m_template
     *
     * @return the value of _template.m_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getmTemplate() {
        return mTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.m_template
     *
     * @param mTemplate the value for _template.m_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setmTemplate(String mTemplate) {
        this.mTemplate = mTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.bas_template
     *
     * @return the value of _template.bas_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getBasTemplate() {
        return basTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.bas_template
     *
     * @param basTemplate the value for _template.bas_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setBasTemplate(String basTemplate) {
        this.basTemplate = basTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.scm_template
     *
     * @return the value of _template.scm_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getScmTemplate() {
        return scmTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.scm_template
     *
     * @param scmTemplate the value for _template.scm_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setScmTemplate(String scmTemplate) {
        this.scmTemplate = scmTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.lua_template
     *
     * @return the value of _template.lua_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getLuaTemplate() {
        return luaTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.lua_template
     *
     * @param luaTemplate the value for _template.lua_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setLuaTemplate(String luaTemplate) {
        this.luaTemplate = luaTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.js_template
     *
     * @return the value of _template.js_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getJsTemplate() {
        return jsTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.js_template
     *
     * @param jsTemplate the value for _template.js_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setJsTemplate(String jsTemplate) {
        this.jsTemplate = jsTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column _template.go_template
     *
     * @return the value of _template.go_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public String getGoTemplate() {
        return goTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column _template.go_template
     *
     * @param goTemplate the value for _template.go_template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    public void setGoTemplate(String goTemplate) {
        this.goTemplate = goTemplate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Template other = (Template) that;
        return (this.getProblemId() == null ? other.getProblemId() == null : this.getProblemId().equals(other.getProblemId()))
            && (this.getcTemplate() == null ? other.getcTemplate() == null : this.getcTemplate().equals(other.getcTemplate()))
            && (this.getCcTemplate() == null ? other.getCcTemplate() == null : this.getCcTemplate().equals(other.getCcTemplate()))
            && (this.getPasTemplate() == null ? other.getPasTemplate() == null : this.getPasTemplate().equals(other.getPasTemplate()))
            && (this.getJavaTemplate() == null ? other.getJavaTemplate() == null : this.getJavaTemplate().equals(other.getJavaTemplate()))
            && (this.getRbTemplate() == null ? other.getRbTemplate() == null : this.getRbTemplate().equals(other.getRbTemplate()))
            && (this.getShTemplate() == null ? other.getShTemplate() == null : this.getShTemplate().equals(other.getShTemplate()))
            && (this.getPyTemplate() == null ? other.getPyTemplate() == null : this.getPyTemplate().equals(other.getPyTemplate()))
            && (this.getPy3Template() == null ? other.getPy3Template() == null : this.getPy3Template().equals(other.getPy3Template()))
            && (this.getPhpTemplate() == null ? other.getPhpTemplate() == null : this.getPhpTemplate().equals(other.getPhpTemplate()))
            && (this.getPlTemplate() == null ? other.getPlTemplate() == null : this.getPlTemplate().equals(other.getPlTemplate()))
            && (this.getCsTemplate() == null ? other.getCsTemplate() == null : this.getCsTemplate().equals(other.getCsTemplate()))
            && (this.getmTemplate() == null ? other.getmTemplate() == null : this.getmTemplate().equals(other.getmTemplate()))
            && (this.getBasTemplate() == null ? other.getBasTemplate() == null : this.getBasTemplate().equals(other.getBasTemplate()))
            && (this.getScmTemplate() == null ? other.getScmTemplate() == null : this.getScmTemplate().equals(other.getScmTemplate()))
            && (this.getLuaTemplate() == null ? other.getLuaTemplate() == null : this.getLuaTemplate().equals(other.getLuaTemplate()))
            && (this.getJsTemplate() == null ? other.getJsTemplate() == null : this.getJsTemplate().equals(other.getJsTemplate()))
            && (this.getGoTemplate() == null ? other.getGoTemplate() == null : this.getGoTemplate().equals(other.getGoTemplate()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProblemId() == null) ? 0 : getProblemId().hashCode());
        result = prime * result + ((getcTemplate() == null) ? 0 : getcTemplate().hashCode());
        result = prime * result + ((getCcTemplate() == null) ? 0 : getCcTemplate().hashCode());
        result = prime * result + ((getPasTemplate() == null) ? 0 : getPasTemplate().hashCode());
        result = prime * result + ((getJavaTemplate() == null) ? 0 : getJavaTemplate().hashCode());
        result = prime * result + ((getRbTemplate() == null) ? 0 : getRbTemplate().hashCode());
        result = prime * result + ((getShTemplate() == null) ? 0 : getShTemplate().hashCode());
        result = prime * result + ((getPyTemplate() == null) ? 0 : getPyTemplate().hashCode());
        result = prime * result + ((getPy3Template() == null) ? 0 : getPy3Template().hashCode());
        result = prime * result + ((getPhpTemplate() == null) ? 0 : getPhpTemplate().hashCode());
        result = prime * result + ((getPlTemplate() == null) ? 0 : getPlTemplate().hashCode());
        result = prime * result + ((getCsTemplate() == null) ? 0 : getCsTemplate().hashCode());
        result = prime * result + ((getmTemplate() == null) ? 0 : getmTemplate().hashCode());
        result = prime * result + ((getBasTemplate() == null) ? 0 : getBasTemplate().hashCode());
        result = prime * result + ((getScmTemplate() == null) ? 0 : getScmTemplate().hashCode());
        result = prime * result + ((getLuaTemplate() == null) ? 0 : getLuaTemplate().hashCode());
        result = prime * result + ((getJsTemplate() == null) ? 0 : getJsTemplate().hashCode());
        result = prime * result + ((getGoTemplate() == null) ? 0 : getGoTemplate().hashCode());
        return result;
    }
}