package cn.edu.nju.software.judge.model;

import lombok.*;

import java.time.LocalDateTime;

/**
 * ////////////////////////////////////////////////////////////////////
 * //                          _ooOoo_                               //
 * //                         o8888888o                              //
 * //                         88" . "88                              //
 * //                         (| ^_^ |)                              //
 * //                         O\  =  /O                              //
 * //                      ____/`---'\____                           //
 * //                    .'  \\|     |//  `.                         //
 * //                   /  \\|||  :  |||//  \                        //
 * //                  /  _||||| -:- |||||-  \                       //
 * //                  |   | \\\  -  /// |   |                       //
 * //                  | \_|  ''\---/''  |   |                       //
 * //                  \  .-\__  `-`  ___/-. /                       //
 * //                ___`. .'  /--.--\  `. . ___                     //
 * //              ."" '<  `.___\_<|>_/___.'  >'"".                  //
 * //            | | :  `- \`.;`\ _ /`;.`/ - ` : | |                 //
 * //            \  \ `-.   \_ __\ /__ _/   .-` /  /                 //
 * //      ========`-.____`-.___\_____/___.-`____.-'========         //
 * //                           `=---='                              //
 * //      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        //
 * //            佛祖保佑       永不宕机     永无BUG                    //
 * ////////////////////////////////////////////////////////////////////
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode
@ToString
public class ProblemModel {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.problem_id
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer problemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.title
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.source
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.memory_limit
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer memoryLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.time_limit
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer timeLimit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.remarks
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String remarks;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.accepted
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer accepted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.submit
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer submit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.solved
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer solved;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.add_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private LocalDateTime addDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.update_datetime
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private LocalDateTime updateDatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.del
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private Integer del;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.description
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.input
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String input;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.output
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String output;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.sample_input
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String sampleInput;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.sample_output
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String sampleOutput;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column _problem.hint
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    private String hint;


}
