package cn.edu.nju.software.judge.model;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * ////////////////////////////////////////////////////////////////////
 * //                          _ooOoo_                               //
 * //                         o8888888o                              //
 * //                         88" . "88                              //
 * //                         (| ^_^ |)                              //
 * //                         O\  =  /O                              //
 * //                      ____/`---'\____                           //
 * //                    .'  \\|     |//  `.                         //
 * //                   /  \\|||  :  |||//  \                        //
 * //                  /  _||||| -:- |||||-  \                       //
 * //                  |   | \\\  -  /// |   |                       //
 * //                  | \_|  ''\---/''  |   |                       //
 * //                  \  .-\__  `-`  ___/-. /                       //
 * //                ___`. .'  /--.--\  `. . ___                     //
 * //              ."" '<  `.___\_<|>_/___.'  >'"".                  //
 * //            | | :  `- \`.;`\ _ /`;.`/ - ` : | |                 //
 * //            \  \ `-.   \_ __\ /__ _/   .-` /  /                 //
 * //      ========`-.____`-.___\_____/___.-`____.-'========         //
 * //                           `=---='                              //
 * //      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^        //
 * //            佛祖保佑       永不宕机     永无BUG                    //
 * ////////////////////////////////////////////////////////////////////
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class UserModel {
        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.user_id
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private Integer userId;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.privilege_id
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private Integer privilegeId;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.user_name
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private String userName;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.nick_name
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private String nickName;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.password
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private String password;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.md5_salt
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private String md5Salt;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.nation
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private String nation;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.create_time
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private LocalDateTime createTime;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.email
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private String email;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.motto
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private String motto;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.avatar
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private String avatar;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.qq
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private String qq;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.school
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private String school;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.blog
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private String blog;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.openId
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private String openid;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.last_login_ip
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private String lastLoginIp;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.last_login_time
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private LocalDateTime lastLoginTime;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.submit
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private Integer submit;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.solved
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private Integer solved;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.state
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private Integer state;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.add_datetime
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private LocalDateTime addDatetime;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.update_datetime
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private LocalDateTime updateDatetime;

        /**
         *
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database column _user.del
         *
         * @mbg.generated Sat Dec 22 11:39:09 CST 2018
         */
        private Integer del;
}
