package cn.edu.nju.software.judge.dao;

import cn.edu.nju.software.judge.beans.Compileinfo;
import cn.edu.nju.software.judge.beans.CompileinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CompileinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _compileinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    long countByExample(CompileinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _compileinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByExample(CompileinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _compileinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByPrimaryKey(Integer submissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _compileinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insert(Compileinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _compileinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insertSelective(Compileinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _compileinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    List<Compileinfo> selectByExampleWithBLOBs(CompileinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _compileinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    List<Compileinfo> selectByExample(CompileinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _compileinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    Compileinfo selectByPrimaryKey(Integer submissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _compileinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") Compileinfo record, @Param("example") CompileinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _compileinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Compileinfo record, @Param("example") CompileinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _compileinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExample(@Param("record") Compileinfo record, @Param("example") CompileinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _compileinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKeySelective(Compileinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _compileinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Compileinfo record);
}