package cn.edu.nju.software.judge.dao;

import cn.edu.nju.software.judge.beans.Contest;
import cn.edu.nju.software.judge.beans.ContestExample;
import cn.edu.nju.software.judge.beans.ContestWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    long countByExample(ContestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByExample(ContestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByPrimaryKey(Integer contestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insert(ContestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insertSelective(ContestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    List<ContestWithBLOBs> selectByExampleWithBLOBs(ContestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    List<Contest> selectByExample(ContestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    ContestWithBLOBs selectByPrimaryKey(Integer contestId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") ContestWithBLOBs record, @Param("example") ContestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") ContestWithBLOBs record, @Param("example") ContestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExample(@Param("record") Contest record, @Param("example") ContestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKeySelective(ContestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(ContestWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _contest
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKey(Contest record);
}