package cn.edu.nju.software.judge.dao;

import cn.edu.nju.software.judge.beans.Cproblem;
import cn.edu.nju.software.judge.beans.CproblemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CproblemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _cproblem
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    long countByExample(CproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _cproblem
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByExample(CproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _cproblem
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByPrimaryKey(Integer cproblemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _cproblem
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insert(Cproblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _cproblem
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insertSelective(Cproblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _cproblem
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    List<Cproblem> selectByExample(CproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _cproblem
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    Cproblem selectByPrimaryKey(Integer cproblemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _cproblem
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") Cproblem record, @Param("example") CproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _cproblem
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExample(@Param("record") Cproblem record, @Param("example") CproblemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _cproblem
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKeySelective(Cproblem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _cproblem
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKey(Cproblem record);
}