package cn.edu.nju.software.judge.dao;

import cn.edu.nju.software.judge.beans.Custominput;
import cn.edu.nju.software.judge.beans.CustominputExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustominputMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _custominput
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    long countByExample(CustominputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _custominput
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByExample(CustominputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _custominput
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByPrimaryKey(Integer submissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _custominput
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insert(Custominput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _custominput
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insertSelective(Custominput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _custominput
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    List<Custominput> selectByExampleWithBLOBs(CustominputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _custominput
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    List<Custominput> selectByExample(CustominputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _custominput
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    Custominput selectByPrimaryKey(Integer submissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _custominput
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") Custominput record, @Param("example") CustominputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _custominput
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Custominput record, @Param("example") CustominputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _custominput
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExample(@Param("record") Custominput record, @Param("example") CustominputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _custominput
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKeySelective(Custominput record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _custominput
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Custominput record);
}