package cn.edu.nju.software.judge.dao;

import cn.edu.nju.software.judge.beans.Runtimeinfo;
import cn.edu.nju.software.judge.beans.RuntimeinfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RuntimeinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _runtimeinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    long countByExample(RuntimeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _runtimeinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByExample(RuntimeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _runtimeinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByPrimaryKey(Integer submissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _runtimeinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insert(Runtimeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _runtimeinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insertSelective(Runtimeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _runtimeinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    List<Runtimeinfo> selectByExampleWithBLOBs(RuntimeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _runtimeinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    List<Runtimeinfo> selectByExample(RuntimeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _runtimeinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    Runtimeinfo selectByPrimaryKey(Integer submissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _runtimeinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") Runtimeinfo record, @Param("example") RuntimeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _runtimeinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Runtimeinfo record, @Param("example") RuntimeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _runtimeinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExample(@Param("record") Runtimeinfo record, @Param("example") RuntimeinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _runtimeinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKeySelective(Runtimeinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _runtimeinfo
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Runtimeinfo record);
}