package cn.edu.nju.software.judge.dao;

import cn.edu.nju.software.judge.beans.Sim;
import cn.edu.nju.software.judge.beans.SimExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SimMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    long countByExample(SimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByExample(SimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insert(Sim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insertSelective(Sim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    List<Sim> selectByExample(SimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    Sim selectByPrimaryKey(Integer sId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") Sim record, @Param("example") SimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExample(@Param("record") Sim record, @Param("example") SimExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKeySelective(Sim record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _sim
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKey(Sim record);
}