package cn.edu.nju.software.judge.dao;

import cn.edu.nju.software.judge.beans.SubmissionCode;
import cn.edu.nju.software.judge.beans.SubmissionCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubmissionCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    long countByExample(SubmissionCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByExample(SubmissionCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByPrimaryKey(Integer submissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insert(SubmissionCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insertSelective(SubmissionCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    List<SubmissionCode> selectByExampleWithBLOBs(SubmissionCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    List<SubmissionCode> selectByExample(SubmissionCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    SubmissionCode selectByPrimaryKey(Integer submissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") SubmissionCode record, @Param("example") SubmissionCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SubmissionCode record, @Param("example") SubmissionCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExample(@Param("record") SubmissionCode record, @Param("example") SubmissionCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKeySelective(SubmissionCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _submission_code
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(SubmissionCode record);
}