package cn.edu.nju.software.judge.dao;

import cn.edu.nju.software.judge.beans.Template;
import cn.edu.nju.software.judge.beans.TemplateExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TemplateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    long countByExample(TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    int deleteByExample(TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    int deleteByPrimaryKey(Integer problemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    int insert(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    int insertSelective(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    List<Template> selectByExampleWithBLOBs(TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    List<Template> selectByExample(TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    Template selectByPrimaryKey(Integer problemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    int updateByExampleSelective(@Param("record") Template record, @Param("example") TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") Template record, @Param("example") TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    int updateByExample(@Param("record") Template record, @Param("example") TemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    int updateByPrimaryKeySelective(Template record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _template
     *
     * @mbg.generated Fri Jan 04 10:02:07 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(Template record);
}