package cn.edu.nju.software.judge.dao;

import cn.edu.nju.software.judge.beans.User;
import cn.edu.nju.software.judge.beans.UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    long countByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    List<User> selectByExample(UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExampleSelective(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByExample(@Param("record") User record, @Param("example") UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table _user
     *
     * @mbg.generated Sat Dec 22 11:39:09 CST 2018
     */
    int updateByPrimaryKey(User record);
}